### ISSUE TITLE
Deploy docs (GitHub Pages) using Travis

### ISSUE THREAD

**Issue by 153957** [HiSPARC/sapphire#177]
Use something like this in `.travis.yml`:
```
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: doc/_build/html
  on:
    branch: master
```
This will deploy docs for commits to master for which the tests pass.
We can also set it to only deploy the docs on tags.

This would allow us to remove the large gh-pages make command:
https://github.com/HiSPARC/sapphire/blob/master/Makefile#L15-L30

And it will automatically force push to the gh-pages branch, overwriting old commits, so there should always be only one commit, keeping that branch very clean.

Example repo where I use this:
https://github.com/153957/153957-theme/
